#7 feat: Update CICD - Deploy Docker Container on EC2

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -66,23 +66,22 @@ jobs:
     needs: build-and-deploy
     
     steps:
-      - name: Check and Install Docker on EC2
-        run: |
-          echo "🔍 Checking Docker..."
-          if ! command -v docker &> /dev/null; then
-            echo "⚠️ Docker not found. Installing..."
-            curl -fsSL https://get.docker.com | sudo sh
-          else
-            echo "✅ Docker is already installed: $(docker --version)"
-          fi
 
       - name: Deploy Docker Container on EC2
         run: |
           echo "🔍 Connecting to EC2 and deploying Docker container..."
           echo "${{ secrets.AWS_EC2_SSH_KEY }}" > ~/.ssh/ec2-key.pem
           chmod 600 ~/.ssh/ec2-key.pem
-          ssh -o StrictHostKeyChecking=no -i ~/.ssh/ec2-key.pem ubuntu@${{ secrets.AWS_EC2_PUBLIC_IP }} << 'EOF'
           
+          ssh -o StrictHostKeyChecking=no -i ~/.ssh/ec2-key.pem ubuntu@${{ secrets.AWS_EC2_PUBLIC_IP }} << 'EOF'
+            echo "🔍 Checking Docker..."
+            if ! command -v docker &> /dev/null; then
+              echo "⚠️ Docker not found. Installing..."
+              curl -fsSL https://get.docker.com | sudo sh
+            else
+              echo "✅ Docker is already installed: $(docker --version)"
+            fi
+
             echo "✅ Connected to EC2"
             echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
 
